First skeleton for the portfolio project
fasaldana/Portfolio_project pull request #1
Opened 2022-02-10 21:11 UTC by fasaldana

In this milestone several files were added:
- Added index.html file with the skeleton of the aplication
- Added some images in a folder named: media/
- Added styles using css for the index file

2022-02-10 22:47 UTC, KDlamini requested changes
### Hi @fasaldana  🙋‍♀️,  

Great job so far! 💯 
You have done a great job setup up your application according to the Figma design. 🥳 
There's always room for improvement. There are some issues that you still need to work on improving your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 
✔️  Correct PR title
✔️  Correct use of Gitflow 
✔️  Commit messages are meaningful
✔️  No linter errors

## Required Changes ♻️
 
 - [ ] Excellent work documenting your README professionally. 👏🏾 
Please kindly add a working [issues](https://github.com/fasaldana/Portfolio_project/issues) link under contributions on your README to make it more professional.
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-10 22:47 UTC, KDlamini commented on style.css
> +}
Kindly use Flexbox to lay out these elements. This project is meant to teach you about using Flexbox to align items on a page. Kindly refer to this [lesson](https://github.com/microverseinc/curriculum-html-css/blob/main/flexbox.md) about an introduction to Flexbox. 

![image](https://user-images.githubusercontent.com/38088818/153504063-1f1c8dfc-1f9e-4ca3-bb6a-859f5d428579.png)

You can practice using Flexbox attributes like `align-items` and `justify-content` on the `nav` element to achieve the desired layout.

2022-02-10 22:47 UTC, KDlamini commented on index.html
> +        <nav>
I think it would be best if you used the `section` or `main` tag for the container for semantic purposes. Like it is explained in [this lesson](https://github.com/microverseinc/curriculum-html-css/blob/main/html5.md) it is the best Html practice to use semantic tags for accessibility purposes.

2022-02-10 22:47 UTC, KDlamini commented on index.html
> +                        </div>
For [semantic](https://github.com/microverseinc/curriculum-html-css/blob/main/html5.md) purposes, please use the `<p>` tag since this is a paragraph. It Html best practice to avoid using `<div>` as much as possible.

2022-02-10 22:47 UTC, KDlamini commented on style.css
> +@media (max-width: 800px) {
Since this project is a mobile-first design please use the `min-width` media query that will handle desktop versions.
You can achieve this by using this media query:
```
@media only screen and (min-width: 992px) {
}
```
NOTE: When using the `min-width` media query, all CSS that is inside the media query will be for desktop view. The rest of the CSS in your `style.css` file will be automatically applied to the mobile view.

Furthermore, your mobile version is not aligned properly. Kindly fix this using Flexbox as per project requirements.
Your mobile version:
![image](https://user-images.githubusercontent.com/38088818/153507316-640a6935-95cb-4bd4-9f90-90891e00b56c.png)

Figma version:
![image](https://user-images.githubusercontent.com/38088818/153507414-6e5e5b6a-769b-453b-ab4b-08b895068a65.png)

You can right-click on your page and click on `inspect` on your browser to check how your application looks on mobile view.

2022-02-11 19:17 UTC, Hope1226 approved these changes
# STATUS: APPROVED :tada:  :confetti_ball: :fireworks: 
Hi @fasaldana , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**To Highlight** :1st_place_medal: 
- Great work on implementing requested changes :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Please add `Acknowledgments` and `License` [README.md](https://github.com/fasaldana/Portfolio_project/tree/skeleton#readme) file

- [ ] [OPTIONAL] Please kindly check inline comments

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-02-11 19:17 UTC, Hope1226 commented on index.html
> +                    <img id="img2" src="./media/illustration-header-mobile.png" alt="">
[OPTIONAL] Great work on adding a background image :+1: . However, you can improve this one by following a few steps below:

- [ ] As it is a background image,  adding it using `CSS` property `background-image` would make much since HTML `img` tag is used when the image has a value or is related to the content. In our case, it is just a background image and has no value to the content. Please refer to the below sample code:
```CSS
selector {
  background: #1c1a19 url(./media/illustration-header-mobile.png) 100% 90% no-repeat;
  }
```

- [ ] Please make sure you choose the correct `selector`, in this case, it should `.presentation`

More on that you can find [here](https://www.w3schools.com/cssref/pr_background-image.asp)

2022-02-11 19:58 UTC, merged