Added functionality to the menu bar
fasaldana/Portfolio_project pull request #10
Opened 2022-02-28 22:52 UTC by fasaldana

In this milestone, a JavaScript file was added with functionality:
- For the menu bar on mobile version.
- For title disappearing when bar is opened.
- For changing the 3 bars into an x when tab is opened.

2022-02-28 23:13 UTC, brytebee requested changes
Hi Team👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Status: Invalid Code Review Request

![](https://media.giphy.com/media/OQeKGexhYKVjLaSzPd/giphy.gif)

_**You have submitted a project, that doesn't contain all the required linters. Kindly add [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) linter file, [Eslint](https://github.com/microverseinc/linters-config/blob/master/javascript/.eslintrc.json).**_

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-03-01 15:56 UTC, Kingstalux requested changes
Hi @fasaldana and @tafaramafemba , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966](https://user-images.githubusercontent.com/85113567/156202568-d27d8db7-d40b-490a-8e48-a923f7cd819a.gif)

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
✔️ Linters are passing
✔️ Good commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-01 15:56 UTC, Kingstalux commented on style.css
> +    padding-left: 40px;
- [ ] Good job designing the mobile menu 👍 but it would be great if you could make it the way it is in the Figma template. The horizontal line below each mobile menu option extends in the Figma template but yours does not. Also, the font size and weight in the Figma templates is a little larger. Kindly address this issue.
- Your design:
![Annotation 2022-03-01 164343](https://user-images.githubusercontent.com/85113567/156202113-3dd65656-7fb6-4842-a6e7-ce2069e626ed.jpg)
- Figma design:
![Annotation 2022-03-01 164403](https://user-images.githubusercontent.com/85113567/156202145-2801530b-420c-44f7-8bbb-f5122a868510.jpg)

2022-03-01 15:56 UTC, Kingstalux commented on index.html
> +                        </li>
- [ ] Good job implementing the mobile menu 👍 but when the user clicks (or taps) any of the mobile menu options, a correct part of the page should be displayed but that is not the case with your menu. Kindly address this issue for a better user interface 💯

2022-03-01 16:56 UTC, mmsesay approved these changes
Hi @fasaldana, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-01 16:56 UTC, mmsesay commented on style.css
>    }
- [OPTIONAL] Good just fixing up the font size for the nav links. However, it will be great to use the correct font family `Inter`.

2022-03-01 16:56 UTC, mmsesay commented on index.html
>              </h2>
- [OPTIONAL] Your contact section is not well aligned as per the design. It will be great if you could work on it>

 You Contact Section       |
:--------------------------------:|
![a 1](https://user-images.githubusercontent.com/39523312/156213226-cf724e14-24b8-45ad-b48b-364abb400a7c.png)

2022-03-01 18:43 UTC, merged